### ISSUE TITLE
renderItem返回的index 不是传入数组的实际index

### ISSUE THREAD

**Issue by Papillonnn** [ZakZheng/react-native-waterflow-list#14]
请问这个怎么解决

**Comment by ZakZheng** [comment]
贴一下代码看看，明天看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月13日(周五) 晚上6:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZakZheng/react-native-waterflow-list] renderItem返回的index 不是传入数组的实际index (#14)




 
请问这个怎么解决
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Papillonnn** [comment]
他是每列数据index都是独立的, 第一列index从0开始递增，然后第二列也是从0开始递增，这个你可以自己测试一下     然后我现在是直接通过数组findIndex方法去拿实际index了

**Comment by Papillonnn** [comment]
`<WaterFlow
      data={photoList}
      keyForItem={item => item.photoId}
      numColumns={2}
      onEndReached={onEndReached}
      columnFlatListProps={{
          style: { marginHorizontal: 2.5 },
      }}
      renderItem={(item, index) => {
             console.log(index);
      }}
  />`

**Comment by ZakZheng** [comment]
确实有这个问题,那用类似这样的方式先实现吧

```
renderItem={({ item }) => {
  const index = list.findIndex(_item => _item.id === item.id)
  ...
}}

```
